#Eksempel på konvertering af dataframe til shape fil:
if(!require(raster)){
  install.packages("raster", repos='http://cran.us.r-project.org')
}
library(raster)
#Eksempel på konvertering af dataframe til shape fil:
if(!require(rgdal)){
  install.packages("rgdal", repos='http://cran.us.r-project.org')
}
library(rgdal)
#Eksempel på konvertering af dataframe til shape fil:
if(!require(tidyverse)){
  install.packages("tidyverse", repos='http://cran.us.r-project.org')
}
library(tidyverse)
#Eksempel på konvertering af dataframe til shape fil:
if(!require(rtop)){
  install.packages("rtop", repos='http://cran.us.r-project.org')
}
library(rtop)
library(raster)
library(rgdal)
library(tidyverse)

# set path
# if you use projects in Rstudio, you don't need to worry about this :-)
rpath = "."
#wd00 <- "/home/hal9000/Documents/Documents/NIVA_Ansaettelse_2021/fish_eDNA_210130/test_example_rtop"
wd00 <- "/home/hal9000/Documents/Documents/NIVA_Ansaettelse_2021/fish_eDNA_210130/rtop_on_virik_eDNA/rtop_tryout_2021November/test_example_rtop"
rpath <- wd00
setwd(wd00)
# read sample data points
file <- "test_points.csv"
df <- read.table(file,sep=",",header=T)
head(df,8)
# add concentrations
conc <- c(1,2,3,5,6,8,10,20)
df$conc <- conc

# create spatial data frame from df
sdf <- df
coordinates(sdf) <- ~lon+lat
proj4string(sdf)<- CRS("EPSG:4326") # set CRS to WGS84
plot(sdf)

# polygons 
poly_obs <-readOGR(rpath, "test_polygons")
crs(poly_obs) # check crs
#plot(poly_obs)
poly_pred <-readOGR(rpath, "test_polygons2")
crs(poly_pred) # check crs

# stream (lines) 
stream <-readOGR(rpath, "test_stream")
crs(stream)
#plot(stream)
# plot poly_pred, poly_obs, stream and points
plot(poly_pred,lty=2,border="#BBBBBB")
lines(poly_obs)
lines(stream,col="blue")
points(sdf,col="red")


# add conc data from points to obs polygons
poly_obs_data <- poly_obs@data 

poly_obs_data<- poly_obs_data %>%
  left_join(select(df,ID,conc),by="ID")

poly_obs@data <- poly_obs_data


#make rtop object
library(rtop)
set.seed(1)

rtopObj	=	createRtopObject(poly_obs, 
                           poly_pred,
                           formulaString =conc~1, 
                           params = list(gDist=TRUE, rresol = 25))


#https://rdrr.io/rforge/rtop/man/rtop-package.html
# There are help-methods available in cases when data are not available as
# shape-files, or when the observations are not part of the shape-files. 
# See readAreaInfo and readAreas.
readAreaInfo(poly_obs)
readAreas(poly_pred)
# A call to rtopVariogram adds the sample variogram to the object, whereas
# rtopFitVariogram fits a variogram model. The last function will call 
# rtopVariogram if rtopObj does not contain a sample variogram.
rtopObj = rtopVariogram(rtopObj)
rtopObj = rtopFitVariogram(rtopObj)
# The function checkVario is useful to produce some diagnostic plots for 
# the sample variogram and the fitted variogram model.
checkVario(rtopObj)


#_______________________________________________________________________________

# Get observations and predictions for 'rtop' example - start
#_______________________________________________________________________________

library(rtop)
library(rgdal)
set.seed(1)
#downloadRtopExampleData()
rpath = system.file("extdata", package = "rtop")
observations = readOGR(rpath, "observations")
predictionLocations=readOGR(rpath, "predictionLocations")
observations$obs = observations$QSUMMER_OB/observations$AREASQKM

#as.data.frame(predictionLocations)
obs2 <-  observations
preL2 <- predictionLocations
rtopObj	=	createRtopObject(observations, 
                           predictionLocations,
                           formulaString = obs~1, 
                           params = list(gDist=TRUE, rresol = 25))
is.null(rtopObj)
#_______________________________________________________________________________
# Get observations and predictions for 'rtop' example - end
#_______________________________________________________________________________


# Compare the pred and obs polygons from the 'rtop' example
# with the polygons for obs and pred generated by your own data
# Looks like the variables 'EZGID' and 'XSTATION' and 'YSTATION'
 # are missing
poly_obs@proj4string
obs2@proj4string

ncol(poly_obs@data)
ncol(obs2@data)

colnames(poly_obs@data)
colnames(obs2@data)
colnames(poly_obs@data) %in% colnames(obs2@data)


ncol(poly_pred@data)
ncol(preL2@data)
colnames(poly_pred@data)
colnames(preL2@data)
colnames(poly_pred@data) %in% colnames(preL2@data)

#_______________________________________________________________________________
rtopObj = rtopFitVariogram(rtopObj)

rtopObj	=	checkVario(rtopObj, cloud = TRUE, identify = TRUE,
                     acor = 0.000001)

rtopObj = checkVario(rtopObj, acor = 0.000001,
                     acomp = data.frame (acl1 = c(2,2,2,2,3,3,3,4,4),
                                         acl2 =c(2,3,4,5,3,4,5,4,5)))

rtopObj = rtopKrige(rtopObj, cv=TRUE)
predictions = rtopObj$predictions
sstot = sum((predictions$obs - mean(predictions$obs))^ 2)
rtopsserr = sum((predictions$obs - predictions$var1.pred)^ 2)
rtoprsq = 1 - rtopsserr/sstot
summary(predictions)
#_______________________________________________________________________________
pred = rtopObj$predictions
is.null(pred)
# this is NULL????? 
# what went wrong?

rtopObj = checkVario(rtopObj, cloud = TRUE,
                     identify = TRUE,
                     acor = 0.000001)


rtopObj = rtopKrige(rtopObj, cv=TRUE)
predictions = rtopObj$predictions
sstot = sum((predictions$obs - mean(predictions$obs))^ 2)
rtopsserr = sum((predictions$obs - predictions$var1.pred)^ 2)
rtoprsq = 1 - rtopsserr/sstot
summary(predictions)
library(automap)
automap::automapPlot(predictions)
plot(predictions)

rtopObj = rtopKrige(rtopObj)


rnet = readOGR(rpath, "riverNetwork")
pred = rtopObj$predictions
#pred$
rnet$pred = pred$var1.pred[match(rnet$EZGA, pred$EZGID)]
spplot(rnet, "pred", col.regions = bpy.colors())


at = seq(0, max(rnet$pred, na.rm =TRUE), 0.01)
cols = bpy.colors(length(at))
cobs = observations@data[, c("XSTATION", "YSTATION", "obs")]
names(cobs) = c("x", "y", "obs")
coordinates(cobs) = ~ x + y
cobs$class = findInterval(cobs$obs, at)


spplot(rnet, "pred", col.regions = bpy.colors(), at = at,
       panel = function(x, y, ...){
         panel.polygonsplot(x, y, ...)
         sp.points(cobs[, "obs"], cex = 1, pch = 16, col = cols[cobs$class])})

writeOGR(rnet, dsn, layer, "ESRI Shapefile")

#_______________________________________________________________________________

# haven't worked out yet how we match the results to the stream network...

# rnet = readOGR(rpath, "riverNetwork")
# rnet$pred = pred$var1.pred[match(rnet$EZGA, pred$EZGID)]


